In [11]:
include("parser.jl")
include("solution.jl")


##===================================================##
##           Data stucture and Parser                ##
##===================================================##

nom_fichier = "655_CH2_EP_RAF_ENP_S52_J1_J2_S01_J1"
type_fichier = "X"
instance = parser(nom_fichier, type_fichier)
solution = init_solution(nom_fichier, type_fichier)


Solution([1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  225, 226, 227, 228, 229, 230, 231, 232, 233, 234], [0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0], [0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0], [0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0])

In [12]:
instance.HPRC_flag

234×4 Array{Bool,2}:
 1  0  0  1
 0  0  0  0
 0  0  1  1
 0  0  0  1
 1  0  0  1
 0  0  1  1
 0  0  0  0
 0  0  0  1
 0  0  1  1
 1  0  0  1
 0  0  0  1
 0  0  0  1
 0  0  1  1
 ⋮         
 1  0  0  1
 0  0  1  1
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  1  1
 0  0  0  0
 0  0  0  0
 1  0  0  1
 0  0  0  0
 0  0  1  1

In [19]:
for i in 1:instance.nb_HPRC
    println("ratio ",i," = " ,instance.HPRC_p[i],"/",instance.HPRC_q[i])
end

ratio 1 = 1/9
ratio 2 = 1/16
ratio 3 = 1/6
ratio 4 = 2/3


In [24]:
V=length(instance.color_code)

234

In [25]:
function greedy(inst::Instances)

# The constructive greedy heuristic starts with
# a partial sequence formed by the remaining cars
# from the previous day.

    # We compute an empty sequence with some cars already scheduled
    sol = init_solution(inst)
    # We have V the set of cars to be scheduled
    len = (sol.n) - (inst.nb_late_prec_day)
    V = collect((inst.nb_late_prec_day+1):(sol.n))

    # Update of Mi
    # For the nb_late_prec_day first cars
    # Update M1, M2, M3
    # for i in 1:(sol.n)
    #     for j in 1:inst.nb_HPRC
    #         if inst.HPRC_flag[j]
    #             M1[i,j] = M1[i,j] + 1
    #         end
    #     end
    #     for j in 1:inst.nb_LPRC
    #         if inst.HPRC_flag[j + inst.nb_HPRC]
    #             M1[i,j + inst.nb_HPRC] = M1[i,j + inst.nb_HPRC] + 1
    #         end
    #     end
    # end



    # The criterion consists in choosing, at each iteration, the car that
    # induces the smallest number of new violations when inserted at the
    # end of the current partial sequence.
    for pos in (inst.nb_late_prec_day+1):(sol.n)

        # I will now compute the number of violations caused by each car
        nb_new_violation = zeros(Int, len)
        for c in V
            for j in 1:inst.nb_HPRC
                if inst.HPRC_flag[pos,j]
                    for i in ((pos - inst.HPRC_q[j])+1):pos
                        if sol.M1[j,i] >= inst.HPRC_p[j]
                            nb_new_violation[v] = nb_new_violation[v] + 1
                        end
                    end
                end
            end
        end

        # I will now compute the set of minimal-rapist's indexes
        cars = [V[1]]
        nb_min = nb_new_violation[1]
        for c in 2:len
            if nb_new_violation[c] < nb_min
                nb_min = nb_new_violation[c]
                cars = [V[c]]
            elseif nb_new_violation[c] == nb_min
                push!(cars, V[c])
            end
        end

        # If |cars| =/= 1, we will pass by tie breaking criterion
        if length(cars) > 1

        end

        # The car is not in the list anymore
        c = cars[1]
        len = len - 1
        filter!(x->x≠c, V)

    end



234-element Array{Int64,1}:
 5
 5
 5
 5
 5
 5
 5
 5
 5
 5
 5
 5
 5
 ⋮
 5
 3
 5
 5
 5
 5
 4
 5
 5
 5
 5
 4

In [95]:
function move(instance,i,j)
    color_code_i=instance.color_code[i]
    flag_HPRC_i=instance.HPRC_flag[i,:]
    if length(instance.LPRC_flag)!=0
        flag_LPRC_i=instance.LPRC_flag[i,:]
        instance.LPRC_flag[i,:]=instance.LPRC_flag[j,:]
        instance.LPRC_flag[j,:]=flag_LPRC_i
    end
    println(instance.color_code[i],";",instance.color_code[j])
    println(instance.HPRC_flag[i,:],";",instance.HPRC_flag[j,:])
    #println(instance.LPRC_flag[i,:],";",instance.LPRC_flag[j,:]) 
    instance.HPRC_flag[i,:]=instance.HPRC_flag[j,:]
    instance.HPRC_flag[j,:]=flag_HPRC_i
    instance.color_code[i]=instance.color_code[j]
    instance.color_code[j]=color_code_i
    #return instance.color_code[i],instance.color_code[j],instance.HPRC_flag[i,:],instance.HPRC_flag[j,:]
end    

move (generic function with 1 method)

In [99]:
c1,c2,f1,f2=move(instance,15,16)
println(c1,";",c2,";",f1,";",f2)

5;4
Bool[0, 0, 1, 1];Bool[0, 0, 0, 0]
4;5;Bool[0, 0, 0, 0];Bool[0, 0, 1, 1]


In [100]:
instance.HPRC_flag[15,:]

4-element Array{Bool,1}:
 0
 0
 0
 0

In [49]:
instance.HPRC_flag

234×4 Array{Bool,2}:
 1  0  0  1
 0  0  0  0
 0  0  1  1
 0  0  0  1
 1  0  0  1
 0  0  1  1
 0  0  0  0
 0  0  0  1
 0  0  1  1
 1  0  0  1
 0  0  0  1
 0  0  0  1
 0  0  1  1
 ⋮         
 1  0  0  1
 0  0  1  1
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  1  1
 0  0  0  0
 0  0  0  0
 1  0  0  1
 0  0  0  0
 0  0  1  1

In [73]:
instance.HPRC_flag[1,:]

4-element Array{Bool,1}:
 1
 0
 0
 1

In [ ]:
for b in instance.nb_late_prec_day:V

end